[2024-07-15T16:02:09.661+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T16:02:09.760+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Postgres_dag.postgres scheduled__2024-07-12T00:00:00+00:00 [queued]>
[2024-07-15T16:02:09.781+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Postgres_dag.postgres scheduled__2024-07-12T00:00:00+00:00 [queued]>
[2024-07-15T16:02:09.782+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-15T16:02:09.873+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): postgres> on 2024-07-12 00:00:00+00:00
[2024-07-15T16:02:09.907+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Postgres_dag', 'postgres', 'scheduled__2024-07-12T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmp11m3thyn']
[2024-07-15T16:02:09.920+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask postgres
[2024-07-15T16:02:09.924+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=285) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T16:02:09.936+0000] {standard_task_runner.py:63} INFO - Started process 288 to run task
[2024-07-15T16:02:10.176+0000] {task_command.py:426} INFO - Running <TaskInstance: Postgres_dag.postgres scheduled__2024-07-12T00:00:00+00:00 [running]> on host 32f997017b5a
[2024-07-15T16:02:10.541+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rayzo' AIRFLOW_CTX_DAG_ID='Postgres_dag' AIRFLOW_CTX_TASK_ID='postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-12T00:00:00+00:00'
[2024-07-15T16:02:10.544+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T16:02:10.620+0000] {sql.py:276} INFO - Executing:  
        Create table if not exists drag_runs(
        dt date,
        dag_id character varying,
        primary key (dt, dag_id)
        )
        
[2024-07-15T16:02:10.640+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T16:02:10.674+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_local` isn't defined
[2024-07-15T16:02:10.697+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Postgres_dag, task_id=postgres, run_id=scheduled__2024-07-12T00:00:00+00:00, execution_date=20240712T000000, start_date=20240715T160209, end_date=20240715T160210
[2024-07-15T16:02:10.899+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task postgres (The conn_id `postgre_local` isn't defined; 288)
[2024-07-15T16:02:10.965+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T16:02:11.051+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T16:02:11.164+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-17T09:26:51.660+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T09:26:52.058+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Postgres_dag.postgres scheduled__2024-07-12T00:00:00+00:00 [queued]>
[2024-07-17T09:26:52.098+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Postgres_dag.postgres scheduled__2024-07-12T00:00:00+00:00 [queued]>
[2024-07-17T09:26:52.104+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-17T09:26:52.373+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): postgres> on 2024-07-12 00:00:00+00:00
[2024-07-17T09:26:52.400+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Postgres_dag', 'postgres', 'scheduled__2024-07-12T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpofhr6khw']
[2024-07-17T09:26:52.410+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask postgres
[2024-07-17T09:26:52.412+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3088) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-17T09:26:52.435+0000] {standard_task_runner.py:63} INFO - Started process 3099 to run task
[2024-07-17T09:26:52.608+0000] {task_command.py:426} INFO - Running <TaskInstance: Postgres_dag.postgres scheduled__2024-07-12T00:00:00+00:00 [running]> on host 67c97fe0936f
[2024-07-17T09:26:53.016+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rayzo' AIRFLOW_CTX_DAG_ID='Postgres_dag' AIRFLOW_CTX_TASK_ID='postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-12T00:00:00+00:00'
[2024-07-17T09:26:53.018+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T09:26:53.044+0000] {sql.py:276} INFO - Executing:  
        Create table if not exists drag_runs(
        dt date,
        dag_id character varying,
        primary key (dt, dag_id)
        )
        
[2024-07-17T09:26:53.059+0000] {base.py:84} INFO - Using connection ID 'Postgres_con' for task execution.
[2024-07-17T09:26:53.076+0000] {base.py:84} INFO - Using connection ID 'Postgres_con' for task execution.
[2024-07-17T09:26:53.113+0000] {sql.py:487} INFO - Running statement:  
        Create table if not exists drag_runs(
        dt date,
        dag_id character varying,
        primary key (dt, dag_id)
        )
        , parameters: None
[2024-07-17T09:26:53.120+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T09:26:53.134+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Postgres_dag, task_id=postgres, run_id=scheduled__2024-07-12T00:00:00+00:00, execution_date=20240712T000000, start_date=20240717T092652, end_date=20240717T092653
[2024-07-17T09:26:53.317+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-17T09:26:53.359+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-07-17T09:26:53.398+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-17T09:26:53.433+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
