[2024-07-15T16:02:09.660+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T16:02:09.762+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Postgres_dag.postgres scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-15T16:02:09.782+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Postgres_dag.postgres scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-15T16:02:09.783+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-15T16:02:09.849+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): postgres> on 2024-07-11 00:00:00+00:00
[2024-07-15T16:02:09.888+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Postgres_dag', 'postgres', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpl50q778k']
[2024-07-15T16:02:09.907+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask postgres
[2024-07-15T16:02:09.916+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=284) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T16:02:09.928+0000] {standard_task_runner.py:63} INFO - Started process 287 to run task
[2024-07-15T16:02:10.134+0000] {task_command.py:426} INFO - Running <TaskInstance: Postgres_dag.postgres scheduled__2024-07-11T00:00:00+00:00 [running]> on host 32f997017b5a
[2024-07-15T16:02:10.504+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rayzo' AIRFLOW_CTX_DAG_ID='Postgres_dag' AIRFLOW_CTX_TASK_ID='postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-15T16:02:10.511+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T16:02:10.590+0000] {sql.py:276} INFO - Executing:  
        Create table if not exists drag_runs(
        dt date,
        dag_id character varying,
        primary key (dt, dag_id)
        )
        
[2024-07-15T16:02:10.613+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T16:02:10.637+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgre_local` isn't defined
[2024-07-15T16:02:10.653+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Postgres_dag, task_id=postgres, run_id=scheduled__2024-07-11T00:00:00+00:00, execution_date=20240711T000000, start_date=20240715T160209, end_date=20240715T160210
[2024-07-15T16:02:10.797+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task postgres (The conn_id `postgre_local` isn't defined; 287)
[2024-07-15T16:02:10.833+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T16:02:10.885+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T16:02:10.968+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-17T09:26:50.434+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T09:26:50.527+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Postgres_dag.postgres scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-17T09:26:50.556+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Postgres_dag.postgres scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-17T09:26:50.559+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-17T09:26:50.616+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): postgres> on 2024-07-11 00:00:00+00:00
[2024-07-17T09:26:50.653+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Postgres_dag', 'postgres', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpc7zu1tn4']
[2024-07-17T09:26:50.667+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask postgres
[2024-07-17T09:26:50.672+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3082) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-17T09:26:50.674+0000] {standard_task_runner.py:63} INFO - Started process 3091 to run task
[2024-07-17T09:26:50.913+0000] {task_command.py:426} INFO - Running <TaskInstance: Postgres_dag.postgres scheduled__2024-07-11T00:00:00+00:00 [running]> on host 67c97fe0936f
[2024-07-17T09:26:51.530+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rayzo' AIRFLOW_CTX_DAG_ID='Postgres_dag' AIRFLOW_CTX_TASK_ID='postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-17T09:26:51.534+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T09:26:51.659+0000] {sql.py:276} INFO - Executing:  
        Create table if not exists drag_runs(
        dt date,
        dag_id character varying,
        primary key (dt, dag_id)
        )
        
[2024-07-17T09:26:51.701+0000] {base.py:84} INFO - Using connection ID 'Postgres_con' for task execution.
[2024-07-17T09:26:51.732+0000] {base.py:84} INFO - Using connection ID 'Postgres_con' for task execution.
[2024-07-17T09:26:51.768+0000] {sql.py:487} INFO - Running statement:  
        Create table if not exists drag_runs(
        dt date,
        dag_id character varying,
        primary key (dt, dag_id)
        )
        , parameters: None
[2024-07-17T09:26:51.798+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T09:26:51.926+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Postgres_dag, task_id=postgres, run_id=scheduled__2024-07-11T00:00:00+00:00, execution_date=20240711T000000, start_date=20240717T092650, end_date=20240717T092651
[2024-07-17T09:26:52.442+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-17T09:26:52.461+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-07-17T09:26:52.482+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-17T09:26:52.594+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
